defaults:
  - cluster: local
  - dataloader: ipsl
  - module: diffusion
  - override hydra/launcher: submitit_slurm
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_
  
#example of override: python run.py environment=cleps

log: False #wandb logging

name: ${module.name}
project: ${module.project}
exp_dir: ${cluster.wandb_dir}${module.project}/${name}/


seed: 0
max_steps: 150000
batch_size: ${cluster.batch_size}
resume: False

save_step_frequency: 50000
log_freq: 100
limit_val_batches: 0
accumulate_grad_batches: 1
debug: False # set to True to debug

#put load_ckpt here

