defaults:
  - cluster: jean_zay_v100
  - dataloader: ipsl
  - module: flow_no_lat_weight
  - override hydra/launcher: submitit_slurm
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_
  
#example of override: python run.py environment=cleps

name: ${module.name}
project: ${module.project}
exp_dir: ${cluster.wandb_dir}${module.project}/${name}/

seed: 0
max_steps: 200000
batch_size: ${module.batch_size}
resume: True

save_step_frequency: 5000
log_freq: 200
limit_val_batches: 0
accumulate_grad_batches: 1
debug: False
log: ${eval:'not ${debug}'} #wandb logging

#put load_ckpt here
#oad_ckpt: /lustre/fsn1/projects/rech/mlr/udy16au/model_output/ipsl_diffusion/${module.name}/checkpoints/checkpoint_global_step=102691.ckpt


# sweeper:
#     params:
#       module: flow_no_climatology_no_delta,flow_sub_pixel_no_delta,flow_sub_pixel_elevation,flow_sub_pixel,flow_conv_head_layernorm,ddpm_elevation_scaled_1000_timesteps