defaults:
  - cluster: jean_zay_v100
  - dataloader: ipsl
  - module: epsilon_no_conv_head_wd_actual
  - override hydra/launcher: submitit_slurm
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_
  
#example of override: python run.py environment=cleps


name: ${module.name}
project: ${module.project}
exp_dir: ${cluster.wandb_dir}${module.project}/${name}/


seed: 0
max_steps: 250000
batch_size: ${module.batch_size}
resume: True

save_step_frequency: 10000
log_freq: 100
limit_val_batches: 0
accumulate_grad_batches: 1
debug: False
log: ${eval:'not ${debug}'} #wandb logging

#put load_ckpt here
#load_ckpt: /gpfsscratch/rech/mlr/udy16au/wandb/ipsl_diffusion/flattened_plev-s0t4u7/checkpoints/epoch=4-step=117705.ckpt

