defaults:
  - cluster: jean_zay_a100
  - dataloader: ipsl
  - module: v_prediction_year_cond_a100
  - override hydra/launcher: submitit_slurm
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_
  
#example of override: python run.py environment=cleps


name: ${module.name}
project: ${module.project}
exp_dir: ${cluster.wandb_dir}${module.project}/${name}/


seed: 0
max_steps: 300000
batch_size: ${module.batch_size}
resume: True

save_step_frequency: 20000
log_freq: 200
limit_val_batches: 0
accumulate_grad_batches: 1
debug: True
log: ${eval:'not ${debug}'} #wandb logging

#put load_ckpt here
load_ckpt: /gpfsscratch/rech/mlr/udy16au/model_output/ipsl_diffusion/v_prediction_year_cond_a100/checkpoints/checkpoint_global_step=20000.ckpt.ckpt

