defaults:
  - _self_
  - environment: jean_zay
  - experiment: one_month_diffusion


  
#to override, use: python run.py environment=cleps


# defaults:
#   - cluster: cleps
#   - dataloader: era5
#   - module: forecast
#   - override hydra/launcher: submitit_slurm
#   - override hydra/job_logging: none
#   - override hydra/hydra_logging: none
#   - _self_


project_name: ipsl_dcpp_diffusion
debug: False


# name: ${module.name}
# project: ${module.project}
# exp_dir: ${cluster.wandb_dir}${module.project}/${name}/

# seed: 0
# max_steps: 300000
# batch_size: ${cluster.batch_size}
# resume: False

# save_step_frequency: 50000
# log_freq: 100
# limit_val_batches: null
# accumulate_grad_batches: 1
# debug: False # set to True to debug
