name: flow_proper_sub_pixel
project: ipsl_diffusion
parent: flow_proper_lat_weight_1
surface_variables: ['tas','npp','nbp','gpp','cVeg','evspsbl','mrfso','mrro','ps','tos']
depth_variables: ['mrsfl','mrsol','mrsll']
plev_variables: ['hur','hus','o3','ta','ua','va','wap','zg']
#batch_size: ${eval:'16 if "${cluster.launcher.slurm_constraint}" == "a100" else 1'} #on a100
delta: True
batch_size: 4
z_normalize: False
flattened_plev: True
mask_value: 0
normalization: 'climatology'

module:
  _target_: ipsl_dcpp.model.diffusion.Diffusion
  num_diffusion_timesteps: 1500
  lr: 3e-4
  weight_decay: 0.01
  betas: [0.9, 0.99]
  num_warmup_steps: 500
  num_cycles: 0.5
  num_training_steps: 150000
  num_inference_steps: 75
  prediction_type: 'v_prediction'
  num_ensemble_members: 2
  num_batch_examples: 2
  p_uncond: 0.0
  scheduler: 'flow'
  num_rollout_steps: 40
  elevation: True
  month_embed: True
  year_embed: True
  lat_weight: True
  s_churn: 0

backbone:
  _target_: ipsl_dcpp.model.pangu.PanguWeather
  soil: False
  plev: False
  conv_head: False
  sub_pixel: True
  lon_resolution: 144
  lat_resolution: 143
  emb_dim: 576
  cond_dim: 256
  num_heads: [6, 12, 12, 6]
  patch_size: [2,2,2]
  two_poles: False
  window_size: [1, 6, 12]   #how is this working when surface channel is only one? 
  depth_multiplier: 2
  position_embs_dim: 0
 # surface_ch: 31
 #31 surface variables and (3*8 level variables) * 3 for prev,current and next
  surface_ch: 103
  output_dim: 34
  level_ch: 0
  #level_ch: 8
  depth_ch: 0
  use_skip: False
  cropped: False
  smoothing: False
