name: v_prediction_year_cond
project: ipsl_diffusion
surface_variables: ['tas','npp','nbp','gpp','cVeg','evspsbl','mrfso','mrro','ps','tos']
depth_variables: ['mrsfl','mrsol','mrsll']
plev_variables: ['hur','hus','o3','ta','ua','va','wap','zg']
batch_size: 1 
flattened_plev: True
z_normalize: False

module:
  _target_: ipsl_dcpp.model.diffusion.Diffusion
  num_diffusion_timesteps: 1000
  lr: 3e-4
  weight_decay: 0.01
  betas: [0.9, 0.99]
  num_warmup_steps: 500
  num_cycles: 0.5
  num_training_steps: 150000
  num_inference_steps: 75
  prediction_type: 'v_prediction'
  num_ensemble_members: 1
  p_uncond: 0.0
  flow_matching: False
  num_rollout_steps: 100

backbone:
  _target_: ipsl_dcpp.model.pangu.PanguWeather
  soil: False
  plev: False
  conv_head: False
  lon_resolution: 144
  lat_resolution: 143
  emb_dim: 576
  cond_dim: 256
  num_heads: [6, 12, 12, 6]
  patch_size: [2,2,2]
  two_poles: False
  window_size: [1, 6, 12]  
  depth_multiplier: 2
  position_embs_dim: 0
 # surface_ch: 31
 #31 surface variables and (3*8 level variables) * 3 for prev,current and next
  surface_ch: 103
  level_ch: 0
  #level_ch: 8
  depth_ch: 0
  use_skip: False
  output_dim: 34
